### ISSUE TITLE
GraphiQL hangs at Loading GraphQL Playground

### ISSUE THREAD

**Issue by xshyne88** [absinthe-graphql/absinthe_plug#199] opened 2019-02-18 16:51 UTC
Hi there,
```
   scope "/graphiql" do
    pipe_through([:api, :public, :absinthe])

    forward(
      "/",
      Absinthe.Plug.GraphiQL,
      schema: docsWeb.Schema,
      json_codec: Jason,
      interface: :playground,
      socket: docsWeb.UserSocket,
      pipeline: {ApolloTracing.Pipeline, :plug}
    )
```
   this is our router.ex, when we comment out interface and not use the graph-cool interface the playground loads just fine, otherwise it hangs on loading graphql playground and this is the javascript error we get

```
Uncaught SyntaxError: Unexpected end of input
graphiql:69 Uncaught ReferenceError: GraphQLPlayground is not defined
    at graphiql:69
```

 (I should note these error messages differ accross browsers but all have to do with graphiql)

Our team tried this across different browsers, machines and os's. We originally thought it was a browser cacheing issue where the middleware CDN had only served part of the file, and our browsers were cacheing it, but we've cleared, disabled, and force refreshed and still no luck.
Apologies in advanced if this isn't absinthe plug related though I'm fairly certain it is because we aren't having issues loading the graphcool interface on other services.

If we comment out the ```interface: :playground``` and load the non graphcool version, it loads just fine, which is also weird. 
Thanks in advance for any help!!

Side note: these absinthe libraries are absolutely excellent and we've had almost no problems up to this point!

**Comment by maartenvanvliet** [comment] 2019-02-18 16:54
We also hit this since today. Still investigating the what's causing it.

**Comment by bruce** [comment] 2019-02-19 06:00
I can reproduce this as well, on a project that `absinthe_plug` hasn't been recently updated and after updating `absinthe_plug` to latest (and on `master`):

I'm seeing the following:

```
SyntaxError: missing } after function body[Learn More] middleware.js:1:343596 note: { opened at line 1, column 343516 (middleware.js:1:343516)
ReferenceError: GraphQLPlayground is not defined[Learn More]
```

I'm going to mention this over at https://github.com/absinthe-graphql/absinthe-graphql-playground, in the event @tlvenn or @mgtitimoli have any ideas what might be going on.

**Comment by fredr** [comment] 2019-02-19 07:02
I tried changing to the `:playground`-interface in our project running `absinthe_plug 1.4.6`, but I can't reproduce the problem.

Maybe there is something weird going on with the CDN delivering the js.

Does your middleware.js look broken? 
https://cdn.jsdelivr.net/npm/@absinthe/graphql-playground@1.2.0/build/static/js/middleware.js

**Comment by bruce** [comment] 2019-02-19 07:45
@fredr Yeah, I verified _earlier_ that result of that URL gave us a syntax error, both in browsers and directly, e.g.:

```shell
$ curl -O https://cdn.jsdelivr.net/npm/@absinthe/graphql-playground@1.2.0/build/static/js/middleware.js
$ node --check middleware.js
middleware.js:2
});
 ^
 SyntaxError: Unexpected token )
 ```

(I even devised a [silly local workaround](https://gist.github.com/bruce/238fd196795518d7cd070b78df7a1325).)

Now, however, after some force-refreshes in the browser, everything seems to be fine—and the same terminal command seems fine:

```shell
$ curl -O https://cdn.jsdelivr.net/npm/@absinthe/graphql-playground@1.2.0/build/static/js/middleware.js
$ node --check middleware.js
(exit code 0)
```

I'm not sure if this was a temporary issue with jsdelivr or if, e.g., @tlvenn made a heroic save.

**Comment by bruce** [comment] 2019-02-19 07:52
Can anyone else verify 👍 / 👎 ? 

Regardless, I'll chat with @benwilson512 / @tlvenn about getting out an updated absinthe_plug (and associated graphql-playground, e.g., #188); in the very least we need the HTTPS fix that's in `master` for the `absinthe.plug.graphiql.assets.download` mix task so people can avoid the CDN.

**Comment by tlvenn** [comment] 2019-02-19 09:18
I did not do anything yet but will block some time tomorrow so I can fix any outstanding issues and hopefully we can publish a new version of the playground and absinthe_plug.

**Comment by JonRowe** [comment] 2019-02-19 12:26
I hit this and fixed it with a dns cache flush and a hard refresh, the CDN seems to be returning invalid files some times.

**Comment by benwilson512** [comment] 2019-02-19 17:56
Observing this on my end as well, no amount of hard refreshing seems to fix this. Weird.

**Comment by JonRowe** [comment] 2019-02-19 18:04
@benwilson512 I had to flush my dns to get another server to resolve it.

**Comment by xshyne88** [comment] 2019-02-19 21:31
@jonrowe I tried refreshing my workstation dns cache and still no good.

**Comment by DMeechan** [comment] 2019-02-24 13:45
Began experiencing this on my end today too. Worked fine yesterday, and now today it mysteriously gets stuck on "Loading GraphQL Playground". 

Flushing DNS cache hasn't fixed it. Anyone had any luck with solving this?

**Comment by bruce** [comment] 2019-02-26 22:52
@DMeechan Sorry about the slow response on this; we're working on it. 😬

**Comment by bruce** [comment] 2019-02-28 02:07
In the meantime, if anyone is looking for a GraphiQL client they can use, I recommend: https://altair.sirmuel.design/ (multiple platforms + a Chrome extension at https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja?hl=en)

**Comment by imolorhe** [comment] 2019-03-01 11:58
@bruce Nice to see Altair works well for your needs. If you would like, I can work you through creating a package for mounting an instance of Altair in elixir 🙂 I wouldn't be able to do that, seeing as I have little to no knowledge of elixir. 😅

**Comment by xshyne88** [comment] 2019-04-02 14:34
Any updates on this or maybe a nudge in the right direction of how I would go about trying to get it to work again?

**Comment by maartenvanvliet** [comment] 2019-05-30 07:32
The issue disappeared without intervention on our end. If the same goes for everyone else this issue can be closed?

**Comment by JonRowe** [comment] 2019-05-30 07:49
I think it's worth knowing how this happened so it doesn't happen again, essentially a corrupt cdn caused this right?

**Comment by binaryseed** [comment] 2020-11-26 05:51
Closing since this appears to be resolved

**Closed by binaryseed** 2020-11-26 05:51 UTC
Labels: Type:Bug
