### ISSUE TITLE
 GraphiQL ignores `default_url` value 

### ISSUE THREAD

**Issue by samphilipd** [absinthe-graphql/absinthe_plug#96] opened 2017-08-04 06:33 UTC
Here is where I specified my default_url:

```
 forward "/graphiql",
      Absinthe.Plug.GraphiQL,
      schema: Eggl.Schema,
      default_headers: {__MODULE__, :graphiql_headers},
      default_url: "/graphql"
```

But when I visit `/graphiql`, the URL is always `http://localhost:4000/graphiql` (notice the `i`). I would have expected it to be `http://localhost:4000/graphql`.

This persists across different browsers and even different machines so its not a local storage cache issue.

See also: https://github.com/absinthe-graphql/absinthe/issues/354#event-1192396416

**Comment by jfrolich** [comment] 2017-10-06 11:15
Same problem here

**Comment by uri** [comment] 2017-10-14 19:27
You're probably using **v1.3.x**. Looks like the `default_url` option is only in **v1.4.x**.

**Comment by bruce** [comment] 2017-10-25 08:06
I can't reproduce this on `master` after clearing local storage (GraphiQL Workspace _will_ aggressively use a cached default URL). I can get the default URL to work with a clean local storage. Closing; reopen if this continues to be an issue on v1.4.

**Closed by bruce** 2017-10-25 08:06 UTC
